apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-code
  description: a source code from github
spec:
  type: code
  owner: guest
  url: https://github.com/wangchi16/example-code/
  lifecycle: experimental
